# config/pipelines.yml
- pipeline.id: pipeline_jira
  path.config: "/usr/share/logstash/pipeline/pipeline_jira.conf"

- pipeline.id: pipeline_sample_1
  path.config: "/usr/share/logstash/pipeline/pipeline_sample_1.conf"